---
title: "ERIN"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(here)

```

You should be able to run through this on the cloud with no problems. Or just download it to your computer. The here package function makes sure paths will not break on different computers :)

```{r readdata}

source(here("analysis_code", "read_gazedata.R"))

file_list <- list.files (path=here('gazedata'), pattern=".gazedata") # extract the edfs from path

#switch to folder with gaze data
setwd(here('gazedata'))


merge_dataset <- do.call("rbind", lapply(file_list, FUN=function(files){
    
    for (i in 1:length(files)){ 
      if(file.exists(files[i])){
        message( "now processing:", files[i])
      }
    }
  
  sub=read_gazedata(files)#fread makes reading in files quick
  aol=readxl::read_excel(here("Data","VPT_AOIs_explanations_ER.xlsx"))
  subs=dplyr::left_join(sub, aol)
  
#time is not important
  
  return(as_tibble(subs))}))

# stip the basename to get the actual subject number to merge with behave data
```


```{r start}
# use subject number to determine the group  
#have to strip the basename bc those do not correspond with the excel files
# use subject number to determine the group    
split_sub<-merge_dataset %>%
  dplyr::mutate(subject = map_chr(Basename, function(s) rev(strsplit(s, "-")[[1]][5])))


split_grup <- split_sub %>%
  mutate(subject=as.numeric(as.character(subject)), group=ifelse(subject>200, "ASD", "TD"))
#read in behav file

```

```{r range}
add.numeric <- function(x) (as.numeric(as.character(x))) # trun ranges numeric

# need to split the range values

range_to <- split_grup %>%
    separate(XnumberTob,sep="-", into=c("rangex1num", "rangex2num")) %>%
    separate(YnumberTob,sep="-", into=c("rangey1num", "rangey2num"))  %>%
    separate(XheadTob,sep="-", into=c("rangex1head", "rangex2head")) %>%
    separate(YheadTob,sep="-", into=c("rangey1head", "rangey2head"))%>%
    separate(XbodyTob,sep="-", into=c("rangex1body", "rangex2body"))%>%
    separate(YbodyTob,sep="-", into=c("rangey1body", "rangey2body")) %>%
    mutate_at(c("rangex1num", "rangex2num", "rangey1num","rangey2num", "rangex1head", "rangex2head", "rangey1head", "rangey2head", "rangex1body", "rangex2body", "rangey1body","rangey2body" ), add.numeric)

# the XnumberTob	YnumberTob	XheadTob	YheadTob	XbodyTob	YbodyTob columns seem to indicate the range X and Y coordinates must fall within to indicate a fixation. I used these ranges to if X falls between X and Y range then they fixated. 

AOIs <- range_to %>%
  dplyr::group_by(Condition, Time)%>%
  dplyr::mutate(num_AOI=ifelse(MeanX >= rangex1num &  MeanX <=rangex2num &  MeanY >= rangey1num &  MeanY <= rangey2num, 1, 0), head_AOI=ifelse(MeanX >= rangex1head & MeanX <=rangex2head & MeanY >= rangey1head & MeanY <= rangey2head, 1,0),body_AOI=ifelse(MeanX >= rangex1body & MeanX <=rangex2body & MeanY >= rangey1body & MeanY <= rangey2body, 1, 0))

#The specifics of data organization and aggregation will depend on the design and hypotheses of the specific study. For this example, the fixation locations need to be “gathered” from separate columns into a single column and “NA” values need to be re-coded as not-fixations:
```


```{r gather}
gaze_obj <- gather(AOIs, 
                   key = "object", value = "fix", 
                   num_AOI:body_AOI, factor_key = TRUE) %>%
  dplyr::mutate(Fix=replace_na(fix, FALSE))

gaze_subj <-gaze_obj %>%
  group_by(group, Degree, Anthropomorphic, object, accuracy) %>%
  summarize(sumfix=sum(Fix), meanfix=mean(Fix, na.rm=TRUE)) # fixation
```


```{r plot}
ggplot(gaze_subj, aes(x=as.factor(Degree), meanfix, group=Anthropomorphic, colour=Anthropomorphic)) + geom_line() + geom_point(size=3, shape=23)+ 
  facet_grid(accuracy+group~object)  + 
  theme_gray() +
   labs(x = "degree",y = "Proportion of Fixations", colour = NULL) +
  ggplot2::coord_cartesian(ylim = c(0, 1))
  
  


```

## Including Plots

